name: Deploy to OVH

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy with lftp
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

          lftp -c "
            set sftp:auto-confirm yes;
            set ssl:verify-certificate no;
            open -u $FTP_USER,$FTP_PASSWORD sftp://$FTP_HOST;
            mirror -R --delete --verbose dist/ www/"
